### ISSUE TITLE
TaxonomyEditor btn not working in creation dialog

### ISSUE THREAD

**Issue by larslehners** [sitegeist/Sitegeist.Taxonomy#17]
If you want to use a property in the CreateDialog that references taxonomies, then there is the problem that the button "Toggle Taxonomy Tree" does not open the TaxonomyEditor.

**Expected result:**
If you click on the button "Toggle Taxonomy Tree" in the CreateDialog, the TaxonomyEditor should open.

**Actual result:**
If you click on the button "Toggle Taxonomy Tree" in the CreateDialog, nothing happens.

**Comment by mficzel** [comment]
This was an issue with the neos ui not supporting secondary editors in creation dialog that was fixed with recent Neos versions
