### ISSUE TITLE
Error in Neos 5

### ISSUE THREAD

**Issue by henrik-d** [sitegeist/Sitegeist.Taxonomy#25]
After updating to Neos 5.1 I get the following error when I access /neos/management/taxonomies
`Undeclared arguments passed to ViewHelper Sitegeist\Taxonomy\ViewHelpers\DimensionInformationViewHelper: node, dimension.`

Is this package not compatible with Neos 5 or is it some other issue in my project?

Edit: PR #24 seems to address this issue.

**Comment by henrik-d** [comment]
Carefully asking wether this package is still maintained or if I better fork & edit it myself?

**Comment by mficzel** [comment]
Since #24 is merged this can be closed
