### ISSUE TITLE
Release 1.3.2 does not work with Neos 4.3

### ISSUE THREAD

**Issue by DrillSergeant** [sitegeist/Sitegeist.Taxonomy#33]
When trying to access the backend module you end up in this error message:
`Argument "node" has already been defined, thus it should not be defined again.`

I assume it has to with https://github.com/sitegeist/Sitegeist.Taxonomy/blob/d1341707b1c0bc153a6b7940e1fa0a824261f7ea/Classes/ViewHelpers/DimensionInformationViewHelper.php#L17

Rolling back to version 1.3.0 works with Neos 4.3.

**Comment by mficzel** [comment]
Close this as this is probably not relevant anymore since neos 4.3 is out of service for a while now.
