### ISSUE TITLE
Neos 3.3: No Icons in Backend

### ISSUE THREAD

**Issue by jonnitto** [sitegeist/Sitegeist.Taxonomy#6]
In Neos 3.3 are no icons visible in the backend:

<img width="1829" alt="screenshot 2018-07-12 17 29 13" src="https://user-images.githubusercontent.com/4510166/42643344-37418c28-85f9-11e8-8c50-9cce8c091dce.png">

**Comment by grebaldi** [comment]
I'm closing this, since Neos 3.3 reached its EOL (see: https://www.neos.io/features/release-process.html).

If the issue's persistent in newer Neos versions, please feel free to reopen.
