### ISSUE TITLE
Editor is not working under Neos 8.2

### ISSUE THREAD

**Issue by jonnitto** [sitegeist/Sitegeist.Taxonomy#62]
After an update to Neos 8.2, the console shows the following error on a node with the `Sitegeist.Taxonomy:TaxonomyEditor`:

`Uncaught ReferenceError: regeneratorRuntime is not defined`

Because of that, the whole Editor stopped working: 

<img width="487" alt="image" src="https://user-images.githubusercontent.com/4510166/211355801-398966a3-6fc1-4c55-ac4a-eec8a44bc759.png">

**Comment by mficzel** [comment]
Can confirm the issue ... seems like the build needs an update hopefulkly this is possible in a way that works with neos 7.3 aswell
